# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='invetoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.CharField(max_length=120, null=True)),
                ('Product_Name', models.CharField(max_length=120, null=True)),
                ('Vendor', models.CharField(max_length=120, null=True)),
                ('MRP', models.IntegerField(max_length=120, null=True)),
                ('Batch_Num', models.IntegerField(max_length=120, null=True)),
                ('Batch_Date', models.DateField(max_length=120, null=True)),
                ('Quatity', models.IntegerField(max_length=120, null=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store_Assistant', models.BooleanField(default=False)),
                ('Store_Manager', models.BooleanField(default=False)),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
