# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20181028_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invetoryrecord',
            old_name='Quatity',
            new_name='Quantity',
        ),
    ]
