# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 04:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_permisionsaddinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisionsaddinventory',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
