# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 14:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0005_permisionsaddinventory_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='permisionsEditInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Approval_Status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.invetoryRecord')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
